[build]
  command = "echo 'No build needed for static site'"
  functions = "netlify/functions"
  publish = "public"

[build.environment]
  NODE_VERSION = "18"

# Redirect API calls to functions
[[redirects]]
  from = "/api/gemini"
  to = "/.netlify/functions/gemini"
  status = 200

[[redirects]]
  from = "/api/firebase-config"
  to = "/.netlify/functions/firebase-config"
  status = 200

[[redirects]]
  from = "/api/health"
  to = "/.netlify/functions/health"
  status = 200

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' https://cdn.tailwindcss.com https://cdnjs.cloudflare.com https://www.gstatic.com https://www.gstatic.cn https://www.gstatic.net https://www.gstatic.org https://ajax.googleapis.com https://cdn.jsdelivr.net https://www.gstatic.cn/firebasejs/ https://www.gstatic.com/firebasejs/;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdn.tailwindcss.com https://cdnjs.cloudflare.com https://cdn.jsdelivr.net;
      font-src 'self' https://fonts.gstatic.com data:;
      connect-src 'self' https://generativelanguage.googleapis.com https://*.firebaseapp.com https://*.firebase.com https://firestore.googleapis.com https://identitytoolkit.googleapis.com https://securetoken.googleapis.com;
      img-src 'self' data: https: blob:;
    """



